# R/wasmconverting.R
# R/wasmnonverting.R
# data-raw/labeling.R
# data-raw/recorder.R
# script/R/testing.R
# script/R/stylized.R
# script/R/simulations.R
# script/R/applications.R
# script/python/polysolver.py
# _variables.yml
# https://lotariohw26.github.io/MD_WASMS/r/examples/
# https://lotariohw26.github.io/MD_WASMS/py/examples/
# data-raw/metadata.json
project:
  type: website
  output-dir: docs
  pre-render: prerendr.R
  render:
    - "index.qmd"
    - "presentation.qmd"
    - "paper.qmd"
    - "laws.qmd"
    - "man_bib.qmd"
    - "addendum/Addendum_az.qmd"
    - "addendum/Addendum_ne.qmd"
    - "metaview.qmd"
    - "simulations.qmd"
    - "rigging.qmd"
    - "analyzer.qmd"
    - "restoration.qmd"
    - "randpython.qmd"
    - "tabset.qmd"

website:
  title: "{{< var titls >}}"
  navbar:
    left:
      - text: "Index"
        href: index.qmd
      - text: "Documentation"
        menu:
        - text: "Presentation" 
          href: "presentation.qmd"
        - text: "Addendum 1: Arizona"
          href: "addendum/Addendum_az.qmd"
        - text: "Addendum 2: Nevada"
          href: "addendum/Addendum_ne.qmd"
        - text: "Paper"
          href: paper.qmd
      - text: "Tabset"
        href: tabset.qmd
      - text: Shiny applications
        menu:
          - text: "R2 simulator"
          # href: "{{< var shn1 >}}"
          - text: "Rigging of a natural election"
          #  href: "{{< var shn2 >}}"
          - text: "Election results analyzer"
          #  href: "{{< var shn3 >}}"
          - text: "Restoration of a rigged election"
          #  href: "{{< var shn4 >}}"
      - text: E-books
        menu:
          - text: "Analysis of the 2020 and 2022 General Elections of Clark and Washoe Counties, Nevada"
            href: "https://lotariohw26.github.io/MD_BOOK1"
      - text: Bibliography
        href: man_bib.qmd
      - text: Appendix
        menu:
        - text: "20 laws and 40 isometries "
          href: "laws.qmd"
        - text: "REPL for R"
          href: "https://webr.r-wasm.org/latest/"
        - text: "Simulations"
          href: "simulations.qmd"
        - text: "Rigging"
          href: "rigging.qmd"
        - text: "Analyzer"
          href: "analyzer.qmd"
        - text: "Restoration"
          href: "restoration.qmd"
        - text: "Functions"
          href: "randpython.qmd"
  repo-url: https://github.com/lotariohw26/ManifoldDestiny
  site-url: https://lotariohw26.github.io/ManifoldDestiny/
  reader-mode: false
  repo-actions: [edit]
  page-footer: 
     left: "" 
     right: 
       - icon: github
         href: https://github.com/lotariohw26/ManifoldDestiny
format:
  html:
    toc: true
    toc-depth: 3
    Mainfont: "Arial"
    Font size: 1.2
    Line stretch: 1.5
bibliography: man_bib.bib
# git remote set-url origin https://$GIT_PAT@github.com/lotariohw26/ManifoldDestiny.git
