project:
  type: website
  render:
    - "index.qmd"

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# git remote set-url origin https://$GIT_PAT@github.com/lotariohw26/ManifoldDestiny.git

